# Latest LTS Node release as of 2022.10.19
FROM node:16.18.0-alpine3.16

# Set working directory for image
WORKDIR /app

# Copy package.json and yarn.lock to root directory
#COPY /server/package*.json ./

# Install all necessary packages
#RUN npm install

#ENV PATH=$PATH:./node_modules/.bin

#COPY ./server .